export const Actions = {
    SCREEN_SET_SIZE: 'SCREEN_SET_SIZE',

    MENU_SET_OPEN: 'MENU_SET_OPEN',

    LOGIN_MODAL_SET_OPEN: 'LOGIN_MODAL_SET_OPEN',

    USER_SET: 'USER_SET',
    USER_GET_ME: 'USER_GET_ME',
    USER_ERROR: 'USER_ERROR',
    USER_SET_AVATAR_UPLOADING: 'USER_SET_AVATAR_UPLOADING',
    USER_SET_AVATAR: 'USER_SET_AVATAR',
    USER_SET_ERROR: 'USER_SET_ERROR',
    USER_SET_WS_CONNECTED: 'USER_SET_WS_CONNECTED',

    LOCALIZATION_SET_LANGUAGE_DATA: 'LOCALIZATION_SET_LANGUAGE_DATA',

    ITEM_LIST_GET_START: 'ITEM_LIST_GET_START',
    ITEM_LIST_SET_DATA: 'ITEM_LIST_SET_DATA',
    ITEM_LIST_SET_ITEMS: 'ITEM_LIST_SET_ITEMS',
    ITEM_LIST_ERROR: 'ITEM_LIST_ERROR',
    ITEM_LIST_CLEAR: 'ITEM_LIST_CLEAR',
    ITEM_LIST_SET_DELETED: 'ITEM_LIST_SET_DELETED',
    ITEM_LIST_CHECK_PRELOADED: 'ITEM_LIST_CHECK_PRELOADED',
    ITEM_LIST_LIKES_SET: 'ITEM_LIST_LIKES_SET',
    ITEM_LIST_OLD_SET: 'ITEM_LIST_OLD_SET',

    POST_GET_START: 'POST_GET_START',
    POST_SET: 'POST_SET',
    POST_ERROR: 'POST_ERROR',
    POST_CLEAR: 'POST_CLEAR',
    POST_COMMENTS_LOADING: 'POST_COMMENTS_LOADING',
    POST_COMMENTS_SET: 'POST_COMMENTS_SET',
    POST_COMMENTS_NEW_COMMENTS_SET: 'POST_COMMENTS_NEW_COMMENTS_SET',
    POST_COMMENTS_MY_POSTED_ADD: 'POST_COMMENTS_MY_POSTED_ADD',
    POST_COMMENT_UPLOADING: 'POST_COMMENT_UPLOADING',

    EDITOR_SET_DEFAULT: 'EDITOR_SET_DEFAULT',
    EDITOR_SET_UPLOADING: 'EDITOR_SET_UPLOADING',
    EDITOR_SET_PROGRESS: 'EDITOR_SET_PROGRESS',
    EDITOR_SET_NEW_POST: 'EDITOR_SET_NEW_POST',
    EDITOR_SET_ERROR: 'EDITOR_SET_ERROR',

    BANNERS_SET_SIDE_BANNER_INDEX: 'BANNERS_SET_SIDE_BANNER_INDEX',

    NOTIFICATIONS_ADD: 'NOTIFICATIONS_ADD',

    PAYMENTS_BALANCE_LOADING: 'PAYMENTS_BALANCE_LOADING',
    PAYMENTS_BALANCE_SET: 'PAYMENTS_BALANCE_SET',

    PAYMENTS_TRANSACTIONS_LOADING: 'PAYMENTS_TRANSACTIONS_LOADING',
    PAYMENTS_TRANSACTIONS_SET: 'PAYMENTS_TRANSACTIONS_SET',
    PAYMENTS_WITHDRAW_OPEN: 'PAYMENTS_WITHDRAW_OPEN',

    AUTHOR_LOADING: 'AUTHOR_LOADING',
    AUTHOR_SET: 'AUTHOR_SET',
    AUTHOR_ERROR: 'AUTHOR_ERROR',
    AUTHOR_RELATED_LOADING: 'AUTHOR_RELATED_LOADING',
    AUTHOR_RELATED_SET: 'AUTHOR_RELATED_SET',

    MEDIA_PREVIEW_SET: 'MEDIA_PREVIEW_SET',
    MEDIA_PREVIEW_CLEAR: 'MEDIA_PREVIEW_CLEAR',

    NEWS_SET: 'NEWS_SET',
};

export const Languages = [
    {code: 'ru', label: 'Русский'},
    {code: 'en', label: 'English'},
];


export const REPORT_SPAM = 1;
export const REPORT_PORN = 2;
export const REPORT_SHOCKING = 3;
export const REPORT_EXTREMISM = 4;
export const REPORT_INSULT = 5;


export const ReportReasons = [
    { value: REPORT_SPAM, captionKey: "reportSpam"  },
    { value: REPORT_PORN, captionKey: "reportPorn"  },
    { value: REPORT_SHOCKING, captionKey: "reportShocking"  },
    { value: REPORT_EXTREMISM, captionKey: "reportExtremism"  },
    { value: REPORT_INSULT, captionKey: "reportInsult"  },
]

export const reportStatus = {
    ACTIVE: 'active',
    ACCEPTED: 'accepted',
    REJECTED: 'rejected'
}

export const errorCode = {
    UNEXPECTED_ERROR: -1,
    CREATE_POST_MEDIA_BAD_MIMETYPE: 101,
    CREATE_POST_MEDIA_TOO_BIG: 102,
    CREATE_POST_MEDIA_TOO_HEAVY: 103,
    CREATE_POST_MEDIA_EMPTY: 104,
    CREATE_POST_CAPTION_TOO_LONG: 105,
    UPDATE_ME_NICKNAME_REQUIRED: 201,
    UPDATE_ME_NICKNAME_EXISTS: 202,
    UPDATE_ME_NICKNAME_TOO_SHORT: 203,
    UPDATE_ME_NICKNAME_TOO_LONG: 204,
    UPDATE_ME_AVATAR_PROCESSING_ERROR: 205,
    UPDATE_ME_NICKNAME_OR_AVATAR_REQUIRED: 206,
    RECAPTCHA_INVALID: 301,
    CREATE_COMMENT_TEXT_OR_MEDIA_REQUIRED: 401,
    CREATE_COMMENT_TEXT_TOO_LONG: 402,
    CREATE_COMMENT_INVALID_REPLY_ON: 403,
    CONFIRM_PAYMENT_STATUS_NOT_ALLOWED: 501,
    CREATE_PAYMENT_START_DATE_MUST_BE_EQUAL_END_DATE_OF_PREV_PAYMENT: 502,
    PAYMENT_WITHDRAW_IN_PROCESS: 503,
    PAYMENT_WITHDRAW_RECIPIENT_IS_REQUIRED: 504,
    PAYMENT_WITHDRAW_VALUE_IS_REQUIRED: 505,
    PAYMENT_WITHDRAW_RECIPIENT_IS_NOT_VALID: 506,
    PAYMENT_WITHDRAW_NOT_ENOUGH_TOKENS: 507,
    PAYMENT_WITHDRAW_ZERO_VALUE: 508,
    PAYMENT_WALLET_NOT_FOUND: 509,
}

export const BannerSettings = {
    CONTENT_BANNER_FREQUENCY: 5,
    CONTENT_BANNER_UPDATE_INTERVAL: 2000,
}

export const restrictedNicknames = [
    'memeus',
    'm',
    'api',
    'oauth',
    'admin',
    'login',
    'logout',
    'best',
    'fresh',
    'hot',
    'about',
    'faq',
    'success',
    'lentach',
    'signin',
    'signup',
    'manage'
]
